// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_API.Models;

#nullable disable

namespace Web_API.Migrations
{
    [DbContext(typeof(TrainingInstituteDBContext))]
    partial class TrainingInstituteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Web_API.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assessmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<DateTime>("AssessmentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("assessmentDate");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrollmentID");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("instructorID");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("remarks");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("result");

                    b.HasKey("AssessmentId")
                        .HasName("assessmentID");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Assessment");
                });

            modelBuilder.Entity("Web_API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Parent_categoryID");

                    b.HasKey("CategoryId")
                        .HasName("categoryID");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Web_API.Models.CertificationRequiredCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificationTrackId")
                        .HasColumnType("int")
                        .HasColumnName("certificationTrackID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseID");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isMandatory");

                    b.Property<int?>("SequenceOrder")
                        .HasColumnType("int")
                        .HasColumnName("sequenceOrder");

                    b.HasKey("Id")
                        .HasName("certReqCourseID");

                    b.HasIndex("CertificationTrackId");

                    b.HasIndex(new[] { "CourseId", "CertificationTrackId" }, "Certification_Required_Course_unique_comb")
                        .IsUnique();

                    b.ToTable("Certification_Required_Course");
                });

            modelBuilder.Entity("Web_API.Models.CertificationStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("statusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("StatusId")
                        .HasName("Certification_Status_pk");

                    b.ToTable("Certification_Status");
                });

            modelBuilder.Entity("Web_API.Models.CertificationTrack", b =>
                {
                    b.Property<int>("CertificationTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("certificationTrackID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificationTrackId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.Property<int?>("ValidityPeriod")
                        .HasColumnType("int")
                        .HasColumnName("validityPeriod");

                    b.HasKey("CertificationTrackId")
                        .HasName("certificationID");

                    b.ToTable("Certification_Track");
                });

            modelBuilder.Entity("Web_API.Models.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("classroomID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassroomId"));

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("building");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("floor");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ClassroomId")
                        .HasName("classroomID");

                    b.ToTable("Classroom");
                });

            modelBuilder.Entity("Web_API.Models.ClassroomEquipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("equipmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int")
                        .HasColumnName("classroomID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("equipmentType");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("EquipmentId", "ClassroomId")
                        .HasName("equipmentID");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Classroom_Equipment");
                });

            modelBuilder.Entity("Web_API.Models.Coordinator", b =>
                {
                    b.Property<int>("CoordinatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("coordinatorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoordinatorId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("userID");

                    b.HasKey("CoordinatorId")
                        .HasName("coordinatorID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Coordinator");
                });

            modelBuilder.Entity("Web_API.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryID");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("courseCode");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<decimal>("DurationHours")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("durationHours");

                    b.Property<decimal>("EnrollmentFee")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("enrollmentFee");

                    b.Property<string>("EquipmentRequirements")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("equipmentRequirements");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int")
                        .HasColumnName("maxCapacity");

                    b.Property<int?>("PrerequisiteCourseId")
                        .HasColumnType("int")
                        .HasColumnName("prerequisiteCourseID");

                    b.Property<int>("SubjectAreaId")
                        .HasColumnType("int")
                        .HasColumnName("subjectAreaID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.HasKey("CourseId")
                        .HasName("courseID");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PrerequisiteCourseId");

                    b.HasIndex("SubjectAreaId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Web_API.Models.CourseSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sessionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int")
                        .HasColumnName("classroomID");

                    b.Property<int>("CoordinatorId")
                        .HasColumnType("int")
                        .HasColumnName("coordinatorID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CurrentEnrollment")
                        .HasColumnType("int")
                        .HasColumnName("currentEnrollment");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("endTime");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("instructorID");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int")
                        .HasColumnName("maxCapacity");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime")
                        .HasColumnName("sessionDate");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("startTime");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.HasKey("SessionId")
                        .HasName("sessionID");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CoordinatorId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StatusId");

                    b.ToTable("Course_Session");
                });

            modelBuilder.Entity("Web_API.Models.CourseSessionStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("StatusId")
                        .HasName("Course_Session_Status_pk");

                    b.ToTable("Course_Session_Status");
                });

            modelBuilder.Entity("Web_API.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enrollmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DropReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dropReason");

                    b.Property<DateTime>("EnrollmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("enrollmentDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EnrollmentStatusId")
                        .HasColumnType("int")
                        .HasColumnName("enrollmentStatusID");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("sessionID");

                    b.Property<DateTime>("StatusChangedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("statusChangedAt");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int")
                        .HasColumnName("traineeID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.HasKey("EnrollmentId")
                        .HasName("enrollmentID");

                    b.HasIndex("EnrollmentStatusId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TraineeId");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("Web_API.Models.EnrollmentStatus", b =>
                {
                    b.Property<int>("EnrollmentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enrollmentStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentStatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.HasKey("EnrollmentStatusId")
                        .HasName("Enrollment_Status_pk");

                    b.ToTable("Enrollment_Status");
                });

            modelBuilder.Entity("Web_API.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("instructorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime")
                        .HasColumnName("hireDate");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("userID");

                    b.HasKey("InstructorId")
                        .HasName("instructorID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Instructor");
                });

            modelBuilder.Entity("Web_API.Models.InstructorAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("availabilityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("instructorID");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("dayOfWeek");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime")
                        .HasColumnName("effectiveFrom");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime")
                        .HasColumnName("effectiveTo");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("endTime");

                    b.Property<bool>("IsRecurring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isRecurring");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("startTime");

                    b.HasKey("AvailabilityId", "InstructorId")
                        .HasName("availabilityID");

                    b.HasIndex("InstructorId");

                    b.ToTable("Instructor_Availability");
                });

            modelBuilder.Entity("Web_API.Models.InstructorExpertise", b =>
                {
                    b.Property<int>("ExpertiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("expertiseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpertiseId"));

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("instructorID");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("proficiencyLevel");

                    b.Property<int>("SubjectAreaId")
                        .HasColumnType("int")
                        .HasColumnName("subjectAreaID");

                    b.HasKey("ExpertiseId")
                        .HasName("ID");

                    b.HasIndex("SubjectAreaId");

                    b.HasIndex(new[] { "InstructorId", "SubjectAreaId" }, "Instructor_Expertise_unique_comb")
                        .IsUnique();

                    b.ToTable("Instructor_Expertise");
                });

            modelBuilder.Entity("Web_API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("isRead");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime")
                        .HasColumnName("readAt");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("relatedEntityType");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("userID");

                    b.HasKey("NotificationId")
                        .HasName("notificationID");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Web_API.Models.PaymentRecord", b =>
                {
                    b.Property<int>("PaymentRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentRecordID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentRecordId"));

                    b.Property<int>("CoordinatorId")
                        .HasColumnType("int")
                        .HasColumnName("coordinatorID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("dueDate");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrollmentID");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("issuedDate");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("statusID");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("totalAmount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.HasKey("PaymentRecordId")
                        .HasName("paymentRecordID");

                    b.HasIndex("CoordinatorId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("StatusId");

                    b.ToTable("Payment_Record");
                });

            modelBuilder.Entity("Web_API.Models.PaymentStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("statusID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.HasKey("StatusId")
                        .HasName("Payment_Status_pk");

                    b.ToTable("Payment_Status");
                });

            modelBuilder.Entity("Web_API.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<int>("CoordinatorId")
                        .HasColumnType("int")
                        .HasColumnName("coordinatorID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("paymentDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("paymentMethod");

                    b.Property<int>("PaymentRecordId")
                        .HasColumnType("int")
                        .HasColumnName("paymentRecordID");

                    b.HasKey("TransactionId")
                        .HasName("transactionID");

                    b.HasIndex("CoordinatorId");

                    b.HasIndex("PaymentRecordId");

                    b.ToTable("Payment_Transaction");
                });

            modelBuilder.Entity("Web_API.Models.SubjectArea", b =>
                {
                    b.Property<int>("SubjectAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subjectAreaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectAreaId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("SubjectAreaId")
                        .HasName("subjectAreaID");

                    b.ToTable("Subject_Area");
                });

            modelBuilder.Entity("Web_API.Models.Trainee", b =>
                {
                    b.Property<int>("TraineeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("traineeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraineeId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime")
                        .HasColumnName("dateOfBirth");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("emergencyContact");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("userID");

                    b.HasKey("TraineeId")
                        .HasName("traineeID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Trainee");
                });

            modelBuilder.Entity("Web_API.Models.TraineeCertification", b =>
                {
                    b.Property<int>("TraineeCertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("traineeCertID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraineeCertId"));

                    b.Property<DateTime?>("CertificateIssuedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("certificateIssuedDate");

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("certificateNumber");

                    b.Property<int>("CertificationTrackId")
                        .HasColumnType("int")
                        .HasColumnName("certificationTrackID");

                    b.Property<DateTime?>("EligibleDate")
                        .HasColumnType("datetime")
                        .HasColumnName("eligibleDate");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("expiryDate");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("statusID");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int")
                        .HasColumnName("traineeID");

                    b.HasKey("TraineeCertId")
                        .HasName("traineeCertID");

                    b.HasIndex("CertificationTrackId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "TraineeId", "CertificationTrackId" }, "Trainee_Certification_unique_comb")
                        .IsUnique();

                    b.ToTable("Trainee_Certification");
                });

            modelBuilder.Entity("Web_API.Models.TraineeCourseCompletion", b =>
                {
                    b.Property<int>("CompletionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("completionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompletionId"));

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("datetime")
                        .HasColumnName("completionDate");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseID");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("result");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("sessionID");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int")
                        .HasColumnName("traineeID");

                    b.HasKey("CompletionId")
                        .HasName("completionID");

                    b.HasIndex("CourseId");

                    b.HasIndex("TraineeId");

                    b.ToTable("Trainee_Course_Completion");
                });

            modelBuilder.Entity("Web_API.Models.Waitlist", b =>
                {
                    b.Property<int>("WaitlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("waitlistID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WaitlistId"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("addedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expiresAt");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("sessionID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("statusID");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int")
                        .HasColumnName("traineeID");

                    b.HasKey("WaitlistId")
                        .HasName("waitlistID");

                    b.HasIndex("StatusId");

                    b.HasIndex("TraineeId");

                    b.HasIndex(new[] { "SessionId", "TraineeId" }, "Waitlist_unique_comb")
                        .IsUnique();

                    b.ToTable("Waitlist");
                });

            modelBuilder.Entity("Web_API.Models.WaitlistStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("statusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.HasKey("StatusId")
                        .HasName("Waitlist_Status_pk");

                    b.ToTable("Waitlist_Status");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Web_API.Models.Assessment", b =>
                {
                    b.HasOne("Web_API.Models.Enrollment", "Enrollment")
                        .WithMany("Assessments")
                        .HasForeignKey("EnrollmentId")
                        .IsRequired()
                        .HasConstraintName("Enrollment_Assesment_fk");

                    b.HasOne("Web_API.Models.Instructor", "Instructor")
                        .WithMany("Assessments")
                        .HasForeignKey("InstructorId")
                        .IsRequired()
                        .HasConstraintName("Instructor_Assesment_fk");

                    b.Navigation("Enrollment");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Web_API.Models.Category", b =>
                {
                    b.HasOne("Web_API.Models.Category", "ParentCategory")
                        .WithMany("InverseParentCategory")
                        .HasForeignKey("ParentCategoryId")
                        .HasConstraintName("Category_Category_fk");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Web_API.Models.CertificationRequiredCourse", b =>
                {
                    b.HasOne("Web_API.Models.CertificationTrack", "CertificationTrack")
                        .WithMany("CertificationRequiredCourses")
                        .HasForeignKey("CertificationTrackId")
                        .IsRequired()
                        .HasConstraintName("Certification_Track_Certification_Required_Course_fk");

                    b.HasOne("Web_API.Models.Course", "Course")
                        .WithMany("CertificationRequiredCourses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("Course_Certification_Required_Course_fk");

                    b.Navigation("CertificationTrack");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Web_API.Models.ClassroomEquipment", b =>
                {
                    b.HasOne("Web_API.Models.Classroom", "Classroom")
                        .WithMany("ClassroomEquipments")
                        .HasForeignKey("ClassroomId")
                        .IsRequired()
                        .HasConstraintName("Classroom_Classroom_Equipment_fk");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("Web_API.Models.Coordinator", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("Web_API.Models.Coordinator", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Web_API.Models.Course", b =>
                {
                    b.HasOne("Web_API.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("Category_Course_fk");

                    b.HasOne("Web_API.Models.Course", "PrerequisiteCourse")
                        .WithMany("InversePrerequisiteCourse")
                        .HasForeignKey("PrerequisiteCourseId")
                        .HasConstraintName("Course_Course_fk");

                    b.HasOne("Web_API.Models.SubjectArea", "SubjectArea")
                        .WithMany("Courses")
                        .HasForeignKey("SubjectAreaId")
                        .IsRequired()
                        .HasConstraintName("Course_Subject_Area_fk");

                    b.Navigation("Category");

                    b.Navigation("PrerequisiteCourse");

                    b.Navigation("SubjectArea");
                });

            modelBuilder.Entity("Web_API.Models.CourseSession", b =>
                {
                    b.HasOne("Web_API.Models.Classroom", "Classroom")
                        .WithMany("CourseSessions")
                        .HasForeignKey("ClassroomId")
                        .IsRequired()
                        .HasConstraintName("Classroom_Course_Session_fk");

                    b.HasOne("Web_API.Models.Coordinator", "Coordinator")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CoordinatorId")
                        .IsRequired()
                        .HasConstraintName("Coordinator_Course_Session_fk");

                    b.HasOne("Web_API.Models.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("Course_Course_Session_fk");

                    b.HasOne("Web_API.Models.Instructor", "Instructor")
                        .WithMany("CourseSessions")
                        .HasForeignKey("InstructorId")
                        .IsRequired()
                        .HasConstraintName("Instructor_Course_Session_fk");

                    b.HasOne("Web_API.Models.CourseSessionStatus", "Status")
                        .WithMany("CourseSessions")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("Course_Session_Status_Course_Session_fk");

                    b.Navigation("Classroom");

                    b.Navigation("Coordinator");

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Web_API.Models.Enrollment", b =>
                {
                    b.HasOne("Web_API.Models.EnrollmentStatus", "EnrollmentStatus")
                        .WithMany("Enrollments")
                        .HasForeignKey("EnrollmentStatusId")
                        .IsRequired()
                        .HasConstraintName("Enrollment_Status_Enrollment_fk");

                    b.HasOne("Web_API.Models.CourseSession", "Session")
                        .WithMany("Enrollments")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("Course_Session_Enrollment_fk");

                    b.HasOne("Web_API.Models.Trainee", "Trainee")
                        .WithMany("Enrollments")
                        .HasForeignKey("TraineeId")
                        .IsRequired()
                        .HasConstraintName("Trainee_Enrollment_fk");

                    b.Navigation("EnrollmentStatus");

                    b.Navigation("Session");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Web_API.Models.Instructor", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("Web_API.Models.Instructor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Web_API.Models.InstructorAvailability", b =>
                {
                    b.HasOne("Web_API.Models.Instructor", "Instructor")
                        .WithMany("InstructorAvailabilities")
                        .HasForeignKey("InstructorId")
                        .IsRequired()
                        .HasConstraintName("Instructor_Instructor_Availability_fk");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Web_API.Models.InstructorExpertise", b =>
                {
                    b.HasOne("Web_API.Models.Instructor", "Instructor")
                        .WithMany("InstructorExpertises")
                        .HasForeignKey("InstructorId")
                        .IsRequired()
                        .HasConstraintName("Instructor_Instructor_Expertise_fk");

                    b.HasOne("Web_API.Models.SubjectArea", "SubjectArea")
                        .WithMany("InstructorExpertises")
                        .HasForeignKey("SubjectAreaId")
                        .IsRequired()
                        .HasConstraintName("Subject_Area_Instructor_Expertise_fk");

                    b.Navigation("Instructor");

                    b.Navigation("SubjectArea");
                });

            modelBuilder.Entity("Web_API.Models.Notification", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Web_API.Models.PaymentRecord", b =>
                {
                    b.HasOne("Web_API.Models.Coordinator", "Coordinator")
                        .WithMany("PaymentRecords")
                        .HasForeignKey("CoordinatorId")
                        .IsRequired()
                        .HasConstraintName("Payment_Record_Coordinator_fk");

                    b.HasOne("Web_API.Models.Enrollment", "Enrollment")
                        .WithMany("PaymentRecords")
                        .HasForeignKey("EnrollmentId")
                        .IsRequired()
                        .HasConstraintName("Enrollment_Payment_Record_fk");

                    b.HasOne("Web_API.Models.PaymentStatus", "Status")
                        .WithMany("PaymentRecords")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("Payment_Status_Payment_Record_fk");

                    b.Navigation("Coordinator");

                    b.Navigation("Enrollment");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Web_API.Models.PaymentTransaction", b =>
                {
                    b.HasOne("Web_API.Models.Coordinator", "Coordinator")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("CoordinatorId")
                        .IsRequired()
                        .HasConstraintName("Coordinator_Payment_Transaction_fk");

                    b.HasOne("Web_API.Models.PaymentRecord", "PaymentRecord")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("PaymentRecordId")
                        .IsRequired()
                        .HasConstraintName("Payment_Record_Payment_Transaction_fk");

                    b.Navigation("Coordinator");

                    b.Navigation("PaymentRecord");
                });

            modelBuilder.Entity("Web_API.Models.Trainee", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("Web_API.Models.Trainee", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Web_API.Models.TraineeCertification", b =>
                {
                    b.HasOne("Web_API.Models.CertificationTrack", "CertificationTrack")
                        .WithMany("TraineeCertifications")
                        .HasForeignKey("CertificationTrackId")
                        .IsRequired()
                        .HasConstraintName("Certification_Track_Trainee_Certification_fk");

                    b.HasOne("Web_API.Models.CertificationStatus", "Status")
                        .WithMany("TraineeCertifications")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("Certification_Status_Trainee_Certification_fk");

                    b.HasOne("Web_API.Models.Trainee", "Trainee")
                        .WithMany("TraineeCertifications")
                        .HasForeignKey("TraineeId")
                        .IsRequired()
                        .HasConstraintName("Trainee_Trainee_Certification_fk");

                    b.Navigation("CertificationTrack");

                    b.Navigation("Status");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Web_API.Models.TraineeCourseCompletion", b =>
                {
                    b.HasOne("Web_API.Models.Course", "Course")
                        .WithMany("TraineeCourseCompletions")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("Course_Trainee_Course_Completion_fk");

                    b.HasOne("Web_API.Models.Trainee", "Trainee")
                        .WithMany("TraineeCourseCompletions")
                        .HasForeignKey("TraineeId")
                        .IsRequired()
                        .HasConstraintName("Trainee_Trainee_Course_Completion_fk");

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Web_API.Models.Waitlist", b =>
                {
                    b.HasOne("Web_API.Models.CourseSession", "Session")
                        .WithMany("Waitlists")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("Course_Session_Waitlist_fk");

                    b.HasOne("Web_API.Models.WaitlistStatus", "StatusNavigation")
                        .WithMany("Waitlists")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("Waitlist_Status_Waitlist_fk");

                    b.HasOne("Web_API.Models.Trainee", "Trainee")
                        .WithMany("Waitlists")
                        .HasForeignKey("TraineeId")
                        .IsRequired()
                        .HasConstraintName("Trainee_Waitlist_fk");

                    b.Navigation("Session");

                    b.Navigation("StatusNavigation");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Web_API.Models.Category", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("InverseParentCategory");
                });

            modelBuilder.Entity("Web_API.Models.CertificationStatus", b =>
                {
                    b.Navigation("TraineeCertifications");
                });

            modelBuilder.Entity("Web_API.Models.CertificationTrack", b =>
                {
                    b.Navigation("CertificationRequiredCourses");

                    b.Navigation("TraineeCertifications");
                });

            modelBuilder.Entity("Web_API.Models.Classroom", b =>
                {
                    b.Navigation("ClassroomEquipments");

                    b.Navigation("CourseSessions");
                });

            modelBuilder.Entity("Web_API.Models.Coordinator", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("PaymentRecords");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("Web_API.Models.Course", b =>
                {
                    b.Navigation("CertificationRequiredCourses");

                    b.Navigation("CourseSessions");

                    b.Navigation("InversePrerequisiteCourse");

                    b.Navigation("TraineeCourseCompletions");
                });

            modelBuilder.Entity("Web_API.Models.CourseSession", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("Web_API.Models.CourseSessionStatus", b =>
                {
                    b.Navigation("CourseSessions");
                });

            modelBuilder.Entity("Web_API.Models.Enrollment", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("PaymentRecords");
                });

            modelBuilder.Entity("Web_API.Models.EnrollmentStatus", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Web_API.Models.Instructor", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("CourseSessions");

                    b.Navigation("InstructorAvailabilities");

                    b.Navigation("InstructorExpertises");
                });

            modelBuilder.Entity("Web_API.Models.PaymentRecord", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("Web_API.Models.PaymentStatus", b =>
                {
                    b.Navigation("PaymentRecords");
                });

            modelBuilder.Entity("Web_API.Models.SubjectArea", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("InstructorExpertises");
                });

            modelBuilder.Entity("Web_API.Models.Trainee", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("TraineeCertifications");

                    b.Navigation("TraineeCourseCompletions");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("Web_API.Models.WaitlistStatus", b =>
                {
                    b.Navigation("Waitlists");
                });
#pragma warning restore 612, 618
        }
    }
}
